obj-$(CONFIG_TOUCHSCREEN_FTS)	+= focaltech_core.o
obj-$(CONFIG_TOUCHSCREEN_FTS)	+= focaltech_ctl.o
obj-$(CONFIG_TOUCHSCREEN_FTS)	+= focaltech_gesture.o
obj-$(CONFIG_TOUCHSCREEN_FTS)	+= focaltech_flash.o 
extlibs :=$(PWD)/drivers/input/touchscreen/ft_gesture_32bit_lib_v1.0_20140820.a 
